[package]
name = "zygisk-compat"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
android_logger = "0.13"
anyhow = "1"
bridge = { path = "../bridge" }
fragile = "2.0"
jni-sys = "0.4"
libc = "0.2"
log = "0.4.21"
